# Modulo 1. Ejercicio 1. Curso Desafío de Programación en Python LinkedIn

Nombre: Harlee Liz Ramos

In [449]:
import pandas as pd

In [450]:
df=pd.read_csv('empleados.csv',delimiter=';')

In [451]:
# Análisis de heads
df.head(3)

,Nombre,Apellido,Sexo,Estado_Civil,Edad,Experiencia,Salario,Gerencia,Departamento
0,Alexandro,NaN,Masculino,Soltero(a),22.0,3.0,2423.0,No,Publicidad
1,Carlos,NaN,Masculino,Casado(a),38.0,10.0,3132.0,Sí,NaN
2,Felipa,NaN,Femenino,Soltero(a),26.0,5.0,2639.0,No,Comercial

In [452]:
# Viendo las 20 primeras columns del dataset + headers
print(df.head(20))

       Nombre  Apellido       Sexo   Estado_Civil  Edad  Experiencia  Salario  \
0   Alexandro       NaN  Masculino     Soltero(a)  22.0          3.0   2423.0
1      Carlos       NaN  Masculino      Casado(a)  38.0         10.0   3132.0
2      Felipa       NaN   Femenino     Soltero(a)  26.0          5.0   2639.0
3      Daniel       NaN  Masculino      Casado(a)  35.0         10.0   3122.0
4        John       NaN  Masculino      Casado(a)  35.0         13.0   3431.0
5      Edward       NaN  Masculino     Soltero(a)   NaN          NaN   4500.0
6     Ruperta       NaN   Femenino      Casado(a)  54.0         18.0   3962.0
7       Amaya       NaN   Femenino  Divorciado(a)  22.0          3.0   2450.0
8   Francisca       NaN   Femenino     Soltero(a)  27.0          4.0   2564.0
9      Selena       NaN   Femenino      Casado(a)  24.0          6.0   2709.0
10       Febe       NaN   Femenino      Casado(a)  44.0         22.0   4359.0
11     Ximena       NaN   Femenino     Soltero(a)  58.0         24.0   4532.0
12      David       NaN  Masculino  Divorciado(a)  20.0          1.0   1977.0
13        Max       NaN  Masculino  Divorciado(a)  39.0          8.0   2953.0
14     Selena       NaN   Femenino      Casado(a)  24.0          6.0   2709.0
15        NaN       NaN   Femenino            NaN  44.0         22.0      NaN
16      Paula       NaN   Femenino  Divorciado(a)  55.0         12.0   3306.0
17        Tim       NaN  Masculino  Divorciado(a)  22.0          4.0   2518.0
18     Andrew       NaN  Masculino  Divorciado(a)   NaN         10.0   3194.0
19     Gloria       NaN   Femenino      Casado(a)  31.0         11.0   3267.0

   Gerencia          Departamento
0        No            Publicidad
1        Sí                   NaN
2        No             Comercial
3        No             Comercial
4        Sí  Servicios al cliente
5        No                 Legal
6        No              Producto
7       NaN             Comercial
8        No                    IT
9        Sí          Contabilidad
10       No                   NaN
11       No                 Legal
12       No      Recursos Humanos
13       No                Ventas
14       Sí          Contabilidad
15      NaN                   NaN
16       No              Producto
17       No      Recursos Humanos
18       No              Producto
19       No  Servicios al cliente

In [453]:
print(df.shape)

(251, 9)

In [454]:
print(df.isnull().sum())

Nombre            6
Apellido        251
Sexo             37
Estado_Civil      4
Edad             61
Experiencia       4
Salario           6
Gerencia         21
Departamento     12
dtype: int64

In [455]:
print(df.notnull().sum())

Nombre          245
Apellido          0
Sexo            214
Estado_Civil    247
Edad            190
Experiencia     247
Salario         245
Gerencia        230
Departamento    239
dtype: int64

In [456]:
#Validacion de columnas
df.columns

Index(['Nombre', 'Apellido', 'Sexo', 'Estado_Civil', 'Edad', 'Experiencia',
       'Salario', 'Gerencia', 'Departamento'],
      dtype='object')

In [457]:
#Mapeado de las columnas

COLUMNS=['Nombre', 'Sexo', 'Estado_Civil', 'Edad', 'Experiencia',
       'Salario', 'Gerencia', 'Departamento']

## **1. Limpieza de Columnas** <br>
>Nota. Toda la columna de Apellidos tiene exactamente 251 campos en blanco - por lo que elimino columna

In [458]:
df_NoLastName=df.drop(axis=1,columns=['Apellido'])
print(df_NoLastName.shape)
print(df_NoLastName.columns)

(251, 8)
Index(['Nombre', 'Sexo', 'Estado_Civil', 'Edad', 'Experiencia', 'Salario',
       'Gerencia', 'Departamento'],
      dtype='object')

## **2. Limpieza de Valores en con espacios y pasandolos a NaN** <br>
Casos tipo ' ' o "  "

In [459]:
#Pasando vacio a NaN
df_NaN=df_NoLastName.replace(r'^\s*$', pd.NA, regex=True)
print(df_NaN.isna().sum())

Nombre           6
Sexo            37
Estado_Civil     4
Edad            61
Experiencia      4
Salario          6
Gerencia        21
Departamento    12
dtype: int64

## **Imputación de datos- Relleno de edad** <br>
En este apartado modifico las edades faltantes para no eliminarlas completamente

In [460]:
dummyAge=round(df['Edad'].mean(),0)
print(dummyAge)

df_NaN['Edad']=df_NaN['Edad'].fillna(dummyAge)

33.0

## **3.Limpieza de Valores NaN** <br>
Es esta forma borro todos las filas que contengan un NaN value

In [461]:
#Nota, Declarar las columnas me permite por ejemplo eliminar de ciertas columnas y no borrar de todas.
df_clean = df_NaN.dropna(subset=COLUMNS)
print(df_clean.isna().sum())
print(df_clean.head())

Nombre          0
Sexo            0
Estado_Civil    0
Edad            0
Experiencia     0
Salario         0
Gerencia        0
Departamento    0
dtype: int64
      Nombre       Sexo Estado_Civil  Edad  Experiencia  Salario Gerencia  \
0  Alexandro  Masculino   Soltero(a)  22.0          3.0   2423.0       No
2     Felipa   Femenino   Soltero(a)  26.0          5.0   2639.0       No
3     Daniel  Masculino    Casado(a)  35.0         10.0   3122.0       No
4       John  Masculino    Casado(a)  35.0         13.0   3431.0       Sí
6    Ruperta   Femenino    Casado(a)  54.0         18.0   3962.0       No

           Departamento
0            Publicidad
2             Comercial
3             Comercial
4  Servicios al cliente
6              Producto

In [462]:
#Dataset check
print(df_clean.shape)
print(df_clean.isnull().sum())
print(df_clean.isna().sum())

(191, 8)
Nombre          0
Sexo            0
Estado_Civil    0
Edad            0
Experiencia     0
Salario         0
Gerencia        0
Departamento    0
dtype: int64
Nombre          0
Sexo            0
Estado_Civil    0
Edad            0
Experiencia     0
Salario         0
Gerencia        0
Departamento    0
dtype: int64

## **4. Limpieza de filas duplicadas**

In [463]:
#Identificacion de duplicados
duplicates = df_clean[df.duplicated(keep=False)]
print(duplicates)
print(df_clean.shape)

    Nombre       Sexo Estado_Civil  Edad  Experiencia  Salario Gerencia  \
9   Selena   Femenino    Casado(a)  24.0          6.0   2709.0       Sí
14  Selena   Femenino    Casado(a)  24.0          6.0   2709.0       Sí
64   Lucio  Masculino   Soltero(a)  54.0         12.0   3317.0       No
65   Lucio  Masculino   Soltero(a)  54.0         12.0   3317.0       No

        Departamento
9       Contabilidad
14      Contabilidad
64  Recursos Humanos
65  Recursos Humanos
(191, 8)

/tmp/ipykernel_9394/130892829.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  duplicates = df_clean[df.duplicated(keep=False)]

In [464]:
df_NoDupl=df_clean.drop_duplicates(subset=COLUMNS)
print(df_NoDupl.shape) #Se eliminaron 2 filas
df_NoDupl.head(5)

(189, 8)

,Nombre,Sexo,Estado_Civil,Edad,Experiencia,Salario,Gerencia,Departamento
0,Alexandro,Masculino,Soltero(a),22.0,3.0,2423.0,No,Publicidad
2,Felipa,Femenino,Soltero(a),26.0,5.0,2639.0,No,Comercial
3,Daniel,Masculino,Casado(a),35.0,10.0,3122.0,No,Comercial
4,John,Masculino,Casado(a),35.0,13.0,3431.0,Sí,Servicios al cliente
6,Ruperta,Femenino,Casado(a),54.0,18.0,3962.0,No,Producto

In [465]:
df_clean_sorted=df_NoDupl.sort_values(by=COLUMNS[0],ignore_index=True)

In [466]:
#New Dataset - creando nuevo dataset
file_name="new_empleados.csv"
df_clean_sorted.to_csv(file_name,sep=";",index=False,encoding="utf-8-sig")

## **5. Regresión**

In [467]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [468]:
model1= LinearRegression()

In [469]:
df1=pd.read_csv('salarios.csv',delimiter=';')
print(df1.head())
df1.columns

   Edad  Experiencia  Salario
0  22.0            3     2423
1  26.0            5     2639
2  35.0           10     3122
3  35.0           13     3431
4  54.0           18     3962

Index(['Edad', 'Experiencia', 'Salario'], dtype='object')

In [470]:
print(df1.isnull().sum())

Edad           46
Experiencia     0
Salario         0
dtype: int64

In [471]:
#Datos para test
nullval = df1['Edad'].isnull()

#Datos para training
train_data = df1[df1['Edad'].notna()].copy()

#Datos para el test
test_data  = df1[df1['Edad'].isna()].copy()

In [472]:
#Dataframes para modelo de regresion lineal
X_train = train_data.drop('Edad', axis=1)
y_train = train_data['Edad']

X_test = test_data.drop('Edad', axis=1)

In [473]:
#Check de las shapes de los datos
X_train.shape

(145, 2)

In [474]:
y_train.shape

(145,)

In [475]:
X_test.shape

(46, 2)

In [476]:
model1.fit(X_train, y_train)

LinearRegression()

In [477]:
predictions= model1.predict(X_test)
print(predictions)

[38.75882405 45.11533205 57.24087808 48.97973939 31.74032335 31.87681669
 32.77139668 36.94973869 38.30839603 44.97201404 58.46986675 45.25865006
 64.70353075 25.2342213  26.77031997 57.35007275 61.70585611 24.10132659
 35.54330869 33.21500003 58.74967809 56.37359676 38.21967536 53.08301007
 65.26315343 39.53056003 42.39801738 29.28234602 47.90089339 68.25345479
 37.16812803 64.38222278 26.6815993  40.15160472 28.10850331 47.84629606
 65.76135412 46.89029407 57.15215741 43.57240871 57.34324809 36.00056137
 26.40861263 46.6992034  72.00866745 57.11120941]

In [478]:
test_data  = test_data.assign(Edad=predictions)
print(test_data.head())

         Edad  Experiencia  Salario
13  38.758824           10     3194
15  45.115332           15     3635
18  57.240878           24     4529
19  48.979739           18     3907
20  31.740323            5     2656